import type { MaybePromise } from "./typeUtils.mjs";
import { Option } from "./option.mjs";
import { FailedResult, Result, SucceededResult } from "./result.mjs";


/**
 * Represents one strategy in a resolution pipeline.
 *
 * @return
 * * `FailedResult` for a hard failure that should stop the pipeline
 * * `SucceededResult(SomeOption<TValue>)` when the value was determined
 * * `SucceededResult(NoneOption)` when this strategy could not determine it
 */
export type ResolutionPipelineStep<TValue, TError> =
    () => MaybePromise<Result<Option<TValue>, TError>>;


/**
 * Options that control runResolutionPipeline behavior.
 */
export interface IRunResolutionPipelineOptions<TError> {
    /**
     * Called only when all steps return `SucceededResult(NoneOption)`.
     *
     * @return The error to return when all strategies are exhausted
     */
    onExhausted: () => TError;
}


/**
 * Runs a sequence of fallback strategies used to resolve a value.
 *
 * @param steps - Ordered resolution strategies
 * @param options - Pipeline options
 * @return A FailedResult if any step hard-fails, a SucceededResult if any step
 * resolves a value, or a FailedResult generated by onExhausted when all steps
 * soft-fail with `NoneOption`
 */
export async function runResolutionPipeline<TValue, TError>(
    steps: Iterable<ResolutionPipelineStep<TValue, TError>>,
    options: IRunResolutionPipelineOptions<TError>
): Promise<Result<TValue, TError>> {
    for (const step of steps) {
        const res = await Promise.resolve(step());

        if (res.failed) {
            return res;
        }

        if (res.value.isSome) {
            return new SucceededResult(res.value.value);
        }
    }

    return new FailedResult(options.onExhausted());
}
