import type { MaybePromise } from "./typeUtils.mjs";
import { FailedResult, Result } from "./result.mjs";


////////////////////////////////////////////////////////////////////////////////
// Step Error Types
////////////////////////////////////////////////////////////////////////////////


/**
 * Indicates that the pipeline should stop immediately.  The pipeline returns
 * a FailedResult containing this error.
 */
export interface ITerminateError<TError> {
    readonly kind:  "terminate";
    readonly error: TError;
}


/**
 * Indicates that this step failed to produce a value but the pipeline should
 * continue with subsequent steps.  The error is accumulated and, if all steps
 * fail, the collected errors are passed to the `onExhausted` callback.
 */
export interface IStepError<TError> {
    readonly kind:  "step";
    readonly error: TError;
}


/**
 * Discriminated union representing the two failure modes of a resolution
 * pipeline step.
 */
export type PipelineStepError<TError> = ITerminateError<TError> | IStepError<TError>;


/**
 * Creates a terminate error that stops the pipeline immediately.
 *
 * @param error - The error value
 * @return A FailedResult wrapping a terminate error
 */
export function pipelineTerminate<TError>(error: TError): FailedResult<ITerminateError<TError>> {
    return new FailedResult({ kind: "terminate", error });
}


/**
 * Creates a step error indicating this step failed but the pipeline should
 * continue.
 *
 * @param error - The error value
 * @return A FailedResult wrapping a step error
 */
export function pipelineStep<TError>(error: TError): FailedResult<IStepError<TError>> {
    return new FailedResult({ kind: "step", error });
}


////////////////////////////////////////////////////////////////////////////////
// Step Types
////////////////////////////////////////////////////////////////////////////////


/**
 * Represents one strategy in a synchronous resolution pipeline.
 *
 * @return
 * * `SucceededResult(value)` when the value was determined
 * * `FailedResult({kind: "step", error})` when this step could not determine
 *   the value but the pipeline should continue
 * * `FailedResult({kind: "terminate", error})` for a hard failure that should
 *   stop the pipeline
 */
export type ResolutionPipelineStep<TValue, TError> =
    () => Result<TValue, PipelineStepError<TError>>;


/**
 * Represents one strategy in an asynchronous resolution pipeline.
 *
 * @return
 * * `SucceededResult(value)` when the value was determined
 * * `FailedResult({kind: "step", error})` when this step could not determine
 *   the value but the pipeline should continue
 * * `FailedResult({kind: "terminate", error})` for a hard failure that should
 *   stop the pipeline
 */
export type ResolutionPipelineStepAsync<TValue, TError> =
    () => MaybePromise<Result<TValue, PipelineStepError<TError>>>;


////////////////////////////////////////////////////////////////////////////////
// Options
////////////////////////////////////////////////////////////////////////////////


/**
 * Options that control resolutionPipeline behavior.
 */
export interface IResolutionPipelineOptions<TStepError, TFinalError> {
    /**
     * Called only when all steps return step errors (soft failures).
     *
     * @param stepErrors - The accumulated errors from all steps
     * @return The error to return when all strategies are exhausted
     */
    onExhausted: (stepErrors: Array<TStepError>) => TFinalError;
}


////////////////////////////////////////////////////////////////////////////////
// Pipeline Functions
////////////////////////////////////////////////////////////////////////////////


/**
 * Runs a sequence of fallback strategies used to resolve a value.
 *
 * @param steps - Ordered resolution strategies
 * @param options - Pipeline options
 * @return A SucceededResult if any step resolves a value, a FailedResult
 * containing a terminate error if any step hard-fails, or a FailedResult
 * generated by onExhausted when all steps return step errors.
 */
export function resolutionPipeline<TValue, TError, TFinalError = TError>(
    steps: Iterable<ResolutionPipelineStep<TValue, TError>>,
    options: IResolutionPipelineOptions<TError, TFinalError>
): Result<TValue, TError | TFinalError> {
    const stepErrors: Array<TError> = [];

    for (const step of steps) {
        const res = step();

        if (res.succeeded) {
            return res;
        }

        if (res.error.kind === "terminate") {
            return new FailedResult(res.error.error);
        }

        stepErrors.push(res.error.error);
    }

    return new FailedResult(options.onExhausted(stepErrors));
}


/**
 * Runs a sequence of fallback strategies used to resolve a value.
 *
 * @param steps - Ordered resolution strategies
 * @param options - Pipeline options
 * @return A SucceededResult if any step resolves a value, a FailedResult
 * containing a terminate error if any step hard-fails, or a FailedResult
 * generated by onExhausted when all steps return step errors.
 */
export async function resolutionPipelineAsync<TValue, TError, TFinalError = TError>(
    steps: Iterable<ResolutionPipelineStepAsync<TValue, TError>>,
    options: IResolutionPipelineOptions<TError, TFinalError>
): Promise<Result<TValue, TError | TFinalError>> {
    const stepErrors: Array<TError> = [];

    for (const step of steps) {
        const res = await Promise.resolve(step());

        if (res.succeeded) {
            return res;
        }

        if (res.error.kind === "terminate") {
            return new FailedResult(res.error.error);
        }

        stepErrors.push(res.error.error);
    }

    return new FailedResult(options.onExhausted(stepErrors));
}
